name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:   
  build:
    name: Swift ${{ matrix.swift-version }} on ${{ matrix.os }}
    
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        swift-version: ["5"]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: swift-actions/setup-swift@cdcbe8e35d3801acd82d7109285e6ab22c9212c2
      with:
        swift-version: ${{ matrix.swift-version }}
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
